version: '3.8'
services:
  bolig-java-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: micro
    networks:
      - bolig-network
networks:
  bolig-network: