version: '3.8'
services:
  java-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: micro
    networks:
      - tv4-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  micro-service:
    image: tv4-image
    ports:
      - "8080:8080"
    depends_on:
      java-db:
        condition: service_healthy
    networks:
      - tv4-network
    environment:
      DB_HOST: java-db
      DB_USERNAME: postgres
      DB_PASSWORD: 123


networks:
  tv4-network:
